server:
  port: 8050

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentme
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect