server:
  port: 8060
      
spring:
  datasource:
    url: jdbc:mysql://admin.cbxai9cjf1gl.us-east-1.rds.amazonaws.com:3306/rentme
    username: admin
    password: Rab3Tech     
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect