server:
  port: 8050
      
spring:
  datasource:
    url: jdbc:mysql://rentme.cbxai9cjf1gl.us-east-1.rds.amazonaws.com/rentme
    username: admin
    password: adminadmin
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect